# Generated by Django 3.1.4 on 2020-12-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Merchandises', '0002_auto_20201221_1820'),
        ('Orders', '0003_auto_20201221_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('merchandiseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchandises.merchandise', verbose_name='merchandiseID')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.order', verbose_name='orderID')),
            ],
            options={
                'db_table': 'Includes',
            },
        ),
    ]
