# Generated by Django 3.1.4 on 2020-12-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='會員姓名')),
                ('nickname', models.CharField(max_length=20, verbose_name='會員暱稱')),
                ('phone', models.CharField(max_length=10, verbose_name='電話號碼')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('email', models.EmailField(max_length=100, verbose_name='電子郵件信箱')),
                ('password', models.CharField(max_length=50, verbose_name='密碼')),
                ('activated', models.BooleanField(default=False, verbose_name='驗證狀態')),
            ],
        ),
    ]
