# Generated by Django 3.1.4 on 2020-12-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='Members',
        ),
    ]
