# Generated by Django 3.1.4 on 2020-12-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0004_auto_20201225_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='會員姓名'),
        ),
    ]
