# Generated by Django 3.1.4 on 2020-12-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='Type', max_length=45)),
                ('content', models.CharField(db_column='Content', max_length=300)),
                ('available', models.BooleanField(db_column='Available', default=True)),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.member', verbose_name='memberID')),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
    ]
