# Generated by Django 3.1.4 on 2020-12-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0002_coupon_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_column='Code', default='ABCD123', max_length=150, primary_key=True, serialize=False),
        ),
    ]
