# Generated by Django 3.1.4 on 2020-12-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0004_auto_20201229_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.FloatField(db_column='Type', default=0, max_length=45),
        ),
    ]
