# Generated by Django 3.1.4 on 2020-12-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_auto_20201221_1806'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Orders',
        ),
    ]
