# Generated by Django 3.1.4 on 2020-12-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_auto_20201221_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='merchandise_id',
        ),
    ]
