# Generated by Django 3.1.4 on 2021-06-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0005_auto_20201230_1156'),
        ('Orders', '0010_auto_20210527_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_price',
            field=models.IntegerField(db_column='Discount_Price', default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coupons.coupon'),
        ),
    ]
