# Generated by Django 3.1.4 on 2020-12-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='產品名稱')),
                ('price', models.IntegerField(default=0, verbose_name='價格')),
                ('detail_info', models.CharField(max_length=500, verbose_name='產品描述')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否被刪除')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='封面圖')),
                ('launched', models.BooleanField(default=True, verbose_name='是否發售中')),
            ],
        ),
    ]
