# Generated by Django 3.1.4 on 2020-12-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandises', '0002_auto_20201221_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
    ]
