# Generated by Django 3.1.4 on 2020-12-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_auto_20201228_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='total_price'),
        ),
    ]
